### PR TITLE
Cleanup of how Minechem container blocks drop their inventory when broken.

### PR DESCRIPTION
**Pull request by mctynp**
This change fixes a dupe bug (Issue #98) and removes some unused code. It also includes unit tests.

### CODE REVIEW

**Comment by MFernflower** [comment]
Is there a rock hard reason to include unit testing?? It seems kind of pointless really.

**Comment by MFernflower** [comment]
Had to remove duplicate posts as school computers are shit.

**Comment by AdlyTempleton** [comment]
Thanks a lot for the bug fixes. Sorry I haven't been more active with fixing these, going through some IRL issues right now.

**Comment by mctynp** [comment]
The unit tests can help catch dupe bug regressions if block breakage code is refactored.

Frankly, I'm disturbed by the lack of automated testing support in Forge, and at how test-hostile Minecraft's and Forge's codebases are. I'm used to having tests for all of my code...

**Pull request merged**
