### PR TITLE
Added localization support for all elements, minerals, and molecules. Ad...

### PR DESCRIPTION
**Pull request by mctynp**
...ded names for en_US only.

NOTE: Non-en_US languages will now show names like "en_US:Carbon" or "en_US:Water". Let me know if you would prefer that missing localizations would show with the localization key instead (e.g., as "minechem.element.C" or "minechem.molecule.water"), or some other option.

### CODE REVIEW

**Comment by MFernflower** [comment]
"Let me know if you would prefer that missing localizations would show with the localization key instead" I think that would be a good idea.

**Comment by MFernflower** [comment]
Also @Vexatos will be pleased to hear that someone is working on the localization engine and related stuff.

**Comment by Vexatos** [comment]
I was mentioned? What's happening? ... OOOOH Wow nice cool hooray Work Yay :dancer:
I've got 7 more exams to do in the next 3 weeks, so do not expect me to be fast, I still have to complete translating 3 ~100 000 character mods :|
This should also close #81 .

**Comment by mctynp** [comment]
Ack, merged a dev branch into my forked master repo too soon--didn't mean to add those new changes to this pull request. I'll attempt to clean up this pull request so it's only the localization changes and doesn't include what should be a separate request...

(did I mention I'm new to git, github, and modding?)

**Comment by Vexatos** [comment]
Don't worry, I don't even know Java that well yet (still in process of learning). Simply clean it up. I am looking Forward to translating all the Chemicals!

**Comment by mctynp** [comment]
Ok, looks like it's fixed here--this pull request should be good again, with just the initial localization changes plus the tweak to have missing localizations show the localization key (e.g., "minechem.molecule.water").

**Comment by AdlyTempleton** [comment]
Thanks for the work.

**Pull request merged**
