### PR TITLE
Fix issue #74

### PR DESCRIPTION
**Pull request by nattaku**
Updated RadiationHandler to skip processing of stable elements to help
stacking problems reported in
https://github.com/pixlepix/MineChem/issues/74

### CODE REVIEW

**Comment by jakimfett** [comment]
Any chance you could make a pull request for this against my fork? https://github.com/jakimfett/MineChem

**Comment by jakimfett** [comment]
@nattaku - If you could please make a pull request against my fork of Minechem (https://github.com/jakimfett/MineChem). I'm currently working through the backlog of issues, as pixlepix has handed Minechem off to me.

**Comment by nattaku** [comment]
@jakimfett sorry, new to Git. I just did it

**Comment by jakimfett** [comment]
Thanks! This will be rolled in with the next dev build.

**Pull request closed without merging**
