### PR TITLE
Added NEI support for synthesis and decomposer recipes.

### PR DESCRIPTION
**Pull request by mctynp**
This request requires that an NEI dev jar be used in the build. I modified the build.gradle script to add a hook for one that can be specified in a separate .properties file, and added an example version of said file. I've tested the resulting obfuscated jar on a dedicated server, and with a client both with and without NEI (+CodeChicken dependencies) installed.

### CODE REVIEW

**Comment by AdlyTempleton** [comment]
Would you mind adding a config option for this? Other than that, great work.

**Comment by mctynp** [comment]
What kind of config option?

**Comment by AdlyTempleton** [comment]
Would you be able to add proper support for DecomposerRecipeChance?

**Comment by Vexatos** [comment]
@mctynp Culd you also localize the name of the block shown in the NEI GUI?

**Comment by mctynp** [comment]
Done and done, plus support for the "click the arrow to see all of this machine's recipes" option in NEI. (pull request #117 ).

**Pull request merged**
